### ISSUE TITLE
Could not get environment variable AWS_LAMBDA_RUNTIME_API

### ISSUE THREAD

**Issue by kaushikraj** [aleph0io/aws-lambda-java-base-images#1]
When I create and run the Docker image locally, I get the following error

`
Could not get environment variable AWS_LAMBDA_RUNTIME_API
`

When I host it on the Lambda and test, it shows the following error

`
Error: fork/exec /lambda-entrypoint.sh: exec format error
Runtime.InvalidEntrypoint
`

**Comment by sigpwned** [comment]
> When I create and run the Docker image locally, I get the following error

How are you running the docker image locally? These images are designed as base images for a lambda function, as opposed to running interactively in a local environment. For example, a command like this will fail with the error message you gave:

    docker run -it public.ecr.aws/aleph0io/lambda/java:17.0.4-al2

You can't really test the base image by itself. Instead, you'd need to build a lambda function on top of the base image (e.g., [this example](https://github.com/aleph0io/example-java-lambda-function)), and then run that example locally using [sam](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-start-lambda.html) or similar.

> When I host it on the Lambda and test, it shows the following error

It sounds to me like you're running a local setup and there's a mismatch between the platform of the image you're using and the architecture of the machine it's running on (e.g., x86_64 vs arm64). If my head is on straight, then this is an issue with how downstream images are built (per [similar issues](https://github.com/aws/aws-lambda-base-images/issues/26)) as opposed to an issue with this base image. I hope to release a multi-platform release of this image soon, but for now the published images are x86_64 only.

Hope that helped! Let me know if you find other problems!

**Comment by kaushikraj** [comment]
@sigpwned Apologies for the late reply.

I was able to find the issue and was able to fix it on my end.

In my case, I had arm64 running on amd64 box as you pointed it out. Thanks!

**Comment by sigpwned** [comment]
Glad you got it figured out! I'll close this issue as resolved.

**Comment by sigpwned** [comment]
@tompro Sorry for closing the issue with your question still active! Honestly just didn't notice your comment. I have successfully tested lambda functions built using these base images with [this documented method](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html#images-test-add). I'm not able to address your issue from the information given above. If you'd like more information or guidance, can you open a separate issue with more information? Thank you!
