### ISSUE TITLE
Add support for slim-alpine corretto images that are smaller and simpler

### ISSUE THREAD

**Issue by pjroth** [aleph0io/aws-lambda-java-base-images#12]
The current images use the amazon linux 2 based corretto images.  It would be nice to use the smaller images since I don't require full amazon linux in my lambda images.  

It might be nice to also support slim-al2 as well at the same time for others that want al2.  

Thanks for this great repo!

**Comment by sigpwned** [comment]
These are great suggestions, thank you!
